export const API_ENDPOINT = {
   login : 'https://localhost:7198/Auth/login',
   register : 'https://localhost:7198/Auth/register',
   changePassword : 'https://localhost:7198/Auth/change-password',
   getUserProfile : 'http://localhost:5221/Employee/profiles',
   getEmployeesByFilter : 'https://localhost:7214/Employee/filter-employee',
   getEmployeeByFilter2: 'https://localhost:7214/Employee/filter',
   getEmployeeById : 'https://localhost:7214/Employee/user',
   getAllEmployee : 'http://localhost:5281/Employee/employees',
   createEmployee: 'https://localhost:7214/Employee',
   importEmployee : 'https://localhost:7214/Employee/import-profile',
   updateEmployeeById : 'https://localhost:7214/Employee/{Id}',
   updateEmployee: 'https://localhost:7214/Employee',
   updateEmployeeMedia : 'https://localhost:7214/EmployeeMedia/UpdateMedia',
   importFromOrches : 'http://localhost:5281/Employee/import',
   deleteEmployee: 'https://localhost:7214/Employee',
   searchEmployees: 'https://localhost:7214/Employee/search',
   getAllDepartment : 'https://localhost:7176/Department/',
   getAllSalary : 'http://localhost:5285/SalaryBase/payroll-info',
   getEmployeeID : 'https://localhost:7214/Employee/employeeIdList',
   getAllActivity : 'https://localhost:7030/ActivityRequest/activity-request',
   getAllActivityType : 'http://localhost:5295/Activity',
   getAllProjects : 'https://localhost:7176/Project',
   getAllPositions : 'https://localhost:7176/JobPosition',
   approveActivity : 'https://localhost:7030/ActivityRequest',
   getAllArticle : 'https://localhost:7176/Article/filter-article',
   uploadArticle : 'https://localhost:7176/Article/upload-word',
   getAllProject : 'https://localhost:7176/Project/filter-project',
   getAllAttendace : 'https://localhost:7030/Attendance/filter-attendance',
   createAttendance : 'https://localhost:7030/Attendance',
   getAllActivityFld : 'https://localhost:7030/activities/fields',
   getAllRelative  : 'https://localhost:7214/Relative/{employeeId}',
   getContractByEmployeeId : 'https://localhost:7214/EmployeeContract/employee/{employeeId}',
   createContract : 'https://localhost:7214/EmployeeContract',
   getAllProjectAndTask : 'https://localhost:7176/Project',
   getSalaryInfo : 'https://localhost:7090/SalaryBase/payroll-info',
   getSalaryChange : 'https://localhost:7090/SalaryHist/base/history-details',
   getSalaryPayment : 'https://localhost:7090/SalaryPayment/payment-list',
   BASE_URL: 'https://localhost:7176',
   getTasksByAssignedTo: 'https://localhost:7176/Task/assigned',
   getAllNews : 'https://localhost:7176/Article',
   getEmployeeCount : 'https://localhost:7214/Employee',
   getEmployeeTotal : 'https://localhost:7214/Employee/statistic',
   getGrowthWorkforce : 'https://localhost:7214/Employee/total-employee',
   getStatisticPayroll : 'https://localhost:7090/SalaryBase/statistic',
   getDepartmentPerfomance : 'https://localhost:7176/Task/statistic',
   getEmployeeInDepartment : 'https://localhost:7214/Employee/employee-department',
   getAllEmailByEmployee : 'https://localhost:7062/Email/employee',
   getAllTemplateMail : 'https://localhost:7062/EmailTemplate',
   sendMail : 'http://localhost:5281/Mail/send',
   getPayrollStatistic : 'https://localhost:7090/SalaryBase/statistic',
   getEmployeeSkills : 'https://localhost:7214/EmployeeEvaluation/statistics',
   getFacilities : "https://localhost:7176/Facility",
   getAllJob : "https://localhost:7176/Job?page={page}&pageSize={pageSize}",
   getAllJobInternal : "https://localhost:7176/JobPosition",
   getEducationByFilter : "https://localhost:7214/Education/filter-education",
   updateRelative : 'https://localhost:7214/Relative',
   deleteRelative : 'https://localhost:7214/Relative',
   uploadContract : 'https://localhost:7214/EmployeeContract',
   createDepartment : "https://localhost:7176/Department",
   updateSalaryAdjustment : "http://localhost:5285/SalaryAdjustment/list",
   createProject : "https://localhost:7176/Project",
   createTask : "https://localhost:7176/Task",
   getAllApplied : "https://localhost:7176/Job/CvApplied",
   getSalaryTemplate : "https://localhost:7062/EmailTemplate/D53F5EEB-2527-48CC-906D-9C335252CF05",
   getMailBoxIDList : "https://localhost:7062/Mailbox/ListMailBoxID/{employeeIds}", 
   sendMailList : "https://localhost:7062/Email/sendList",
   getBatchSalary : "https://localhost:7090/SalaryPayment/SalaryPaymentList",
   updateUserProfile : "https://localhost:7198/Auth/profile",
   updateAttendance : 'https://localhost:7030/Attendance',
   pushPayment : 'https://localhost:7090/SalaryPayment/ListPayment',
   updatePaymentStatus : 'https://localhost:7090/SalaryPayment/UpdateStatus',
   loadAllPeriod : 'https://localhost:7214/EvaluationPeriod',
   loadAllCriterias : 'https://localhost:7214/EvaluationCriterion',
   addCriterias : 'https://localhost:7214/EvaluationCriterion',
   addEvaluationEmployee : 'https://localhost:7214/EmployeeEvaluation',
};
