export const API_ENDPOINT = {
   login : 'https://localhost:7198/Auth/login',
   register : 'https://localhost:7198/Auth/register',
   changePassword : 'https://localhost:7198/Auth/change-password',
   getUserProfile : 'http://localhost:5221/Employee/profiles',
   getEmployeesByFilter : 'https://localhost:7214/Employee/filter-employee',
   getEmployeeById : 'https://localhost:7214/Employee/user',
   getAllEmployee : 'http://localhost:5281/Employee/employees',
   createEmployee: 'https://localhost:7214/Employee',
   updateEmployee: 'https://localhost:7214/Employee',
   deleteEmployee: 'https://localhost:7214/Employee',
   searchEmployees: 'https://localhost:7214/Employee/search',
   getAllDepartment : 'https://localhost:7176/Department/',
   getAllSalary : 'http://localhost:5285/SalaryBase/payroll-info',
   getEmployeeID : 'https://localhost:7214/Employee/employeeIdList',
   getAllActivity : 'https://localhost:7030/ActivityRequest/activity-request',
   getAllActivityType : 'http://localhost:5295/Activity',
   getAllProjects : 'https://localhost:7176/Project',
   getAllPositions : 'https://localhost:7176/JobPosition',
   approveActivity : 'https://localhost:7030/ActivityRequest',
   getAllArticle : 'https://localhost:7176/Article/filter-article',
   uploadArticle : 'https://localhost:7176/Article/upload-word',
   getAllProject : 'https://localhost:7176/Project/filter-project',
   getAllAttendace : 'https://localhost:7030/Attendance/filter-attendance',
   createAttendance : 'https://localhost:7030/Attendance',
};
