import { jobGridModel } from './grid.model';

export const JobGriddata: jobGridModel[] = [
  {
    id: '1',
    TenCV: 'Senior Web Developer',
    CongTy: 'Web Technology pvt.Ltd',
    TinhThanh: 'Hà Nội',
    Luong: '15-20 triệu',
    LoaiHinh: 'Toàn thời gian',
    KinhNghiem: '3-5 năm',
    CapBac: 'Senior',
    HanNopCV: '2024-03-30',
    YeuCau: 'Thành thạo Angular, React, Node.js',
    MoTa: 'Phát triển và duy trì các ứng dụng web',
    PhucLoi: 'Lương tháng 13, Bảo hiểm sức khỏe',
    SoLuong: '2',
    Image: 'assets/images/companies/img-1.png',
    Link: 'https://example.com/job1',
    Web: 'https://example.com',
    Nganh: 'Công nghệ thông tin',
    status: 'active'
  },
  {
    id: '2',
    TenCV: 'UI/UX Designer',
    CongTy: 'Creative Design Studio',
    TinhThanh: 'TP.HCM',
    Luong: '12-15 triệu',
    LoaiHinh: 'Toàn thời gian',
    KinhNghiem: '2-3 năm',
    CapBac: 'Middle',
    HanNopCV: '2024-04-15',
    YeuCau: 'Thành thạo Figma, Adobe XD',
    MoTa: 'Thiết kế giao diện người dùng',
    PhucLoi: 'Lương tháng 13, Đào tạo',
    SoLuong: '1',
    Image: 'assets/images/companies/img-2.png',
    Link: 'https://example.com/job2',
    Web: 'https://example.com',
    Nganh: 'Thiết kế',
    status: 'active'
  },
  {
    id: '3',
    TenCV: 'Mobile Developer',
    CongTy: 'Mobile Solutions Inc',
    TinhThanh: 'Đà Nẵng',
    Luong: '18-25 triệu',
    LoaiHinh: 'Toàn thời gian',
    KinhNghiem: '4-6 năm',
    CapBac: 'Senior',
    HanNopCV: '2024-04-30',
    YeuCau: 'Thành thạo React Native, Flutter',
    MoTa: 'Phát triển ứng dụng di động',
    PhucLoi: 'Lương tháng 13, Bảo hiểm sức khỏe',
    SoLuong: '3',
    Image: 'assets/images/companies/img-3.png',
    Link: 'https://example.com/job3',
    Web: 'https://example.com',
    Nganh: 'Công nghệ thông tin',
    status: 'active'
  },
  {
    id: '4',
    TenCV: 'DevOps Engineer',
    CongTy: 'Cloud Solutions Ltd',
    TinhThanh: 'Hà Nội',
    Luong: '20-30 triệu',
    LoaiHinh: 'Toàn thời gian',
    KinhNghiem: '3-5 năm',
    CapBac: 'Senior',
    HanNopCV: '2024-05-15',
    YeuCau: 'Thành thạo Docker, Kubernetes, AWS',
    MoTa: 'Quản lý và tự động hóa hệ thống',
    PhucLoi: 'Lương tháng 13, Bảo hiểm sức khỏe',
    SoLuong: '2',
    Image: 'assets/images/companies/img-4.png',
    Link: 'https://example.com/job4',
    Web: 'https://example.com',
    Nganh: 'Công nghệ thông tin',
    status: 'active'
  },
  {
    id: '5',
    TenCV: 'Marketing Manager',
    CongTy: 'Digital Marketing Agency',
    TinhThanh: 'TP.HCM',
    Luong: '15-20 triệu',
    LoaiHinh: 'Toàn thời gian',
    KinhNghiem: '5-7 năm',
    CapBac: 'Manager',
    HanNopCV: '2024-05-30',
    YeuCau: 'Kinh nghiệm quản lý team marketing',
    MoTa: 'Quản lý chiến dịch marketing',
    PhucLoi: 'Lương tháng 13, Thưởng dự án',
    SoLuong: '1',
    Image: 'assets/images/companies/img-5.png',
    Link: 'https://example.com/job5',
    Web: 'https://example.com',
    Nganh: 'Marketing',
    status: 'active'
  }
];
  